Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -87,11 +87,8 @@ jobs:
             sleep 2
             echo "The PATH ENV is --" && echo $PATH && echo ""
             # yes | "${ANDROID_HOME}"/tools/bin/sdkmanager --licenses
-            "${ANDROID_HOME}"/tools/bin/sdkmanager --update
-            "${ANDROID_HOME}"/tools/bin/sdkmanager 'build-tools;27.0.3'
-            "${ANDROID_HOME}"/tools/bin/sdkmanager 'platform-tools'
-            "${ANDROID_HOME}"/tools/bin/sdkmanager 'tools'
-            "${ANDROID_HOME}"/tools/bin/sdkmanager 'platforms;android-27'
+            # "${ANDROID_HOME}"/tools/bin/sdkmanager --update
+            "${ANDROID_HOME}"/tools/bin/sdkmanager 'build-tools;27.0.3' 'platform-tools' 'tools' 'platforms;android-27' || echo "sdkman installs failed!"
             echo ">>> Initial Disc Space is" && df -hlT
           no_output_timeout: 8m
       - run:
